<?php
declare(strict_types=1);
require __DIR__ . '/Pda.php';

/**
 * Checks this PHP implementation against vectors generated by the published
 * Rust crate. Run the generator first:
 *
 *   cd ../vectors-gen && cargo run --release > ../php/vectors.json
 *   php verify.php vectors.json
 */
$path = $argv[1] ?? 'vectors.json';
if (!is_file($path)) {
    fwrite(STDERR, "no vector file at $path -- run the Rust generator first\n");
    exit(2);
}
$v = json_decode(file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
$program = Base58::decode($v['program_id']);
$fail = 0;
$n = $v['count'];

foreach (['site', 'contract'] as $kind) {
    $bad = 0;
    foreach ($v[$kind] as $row) {
        $i = $row['i'];
        $authority = hash('sha256', "authority-$i", true);
        if ($kind === 'site') {
            $seeds = ['site', $authority];
        } else {
            [$site, ] = Pda::findProgramAddress(['site', $authority], $program);
            $seeds = ['contract', $site, hash('sha256', "payer-$i", true)];
        }
        [$addr, $bump] = Pda::findProgramAddress($seeds, $program);
        if (Base58::encode($addr) !== $row['address'] || $bump !== $row['bump']) {
            $bad++;
            if ($bad <= 3) {
                printf("  MISMATCH %s[%d]\n    rust %s (bump %d)\n    php  %s (bump %d)\n",
                    $kind, $i, $row['address'], $row['bump'], Base58::encode($addr), $bump);
            }
        }
    }
    printf("%-10s %d/%d match%s\n", $kind, $n - $bad, $n, $bad ? '  <-- FAILED' : '');
    $fail += $bad;
}

$m = $v['meter_and_settle'];
$disc = substr(hash('sha256', 'global:meter_and_settle', true), 0, 8);
$expected = bin2hex($disc) . bin2hex(pack('V', $m['page_views']));
printf("%-10s %s\n", 'ix data', $expected === $m['data_hex']
    ? "match ({$expected})"
    : "MISMATCH  rust {$m['data_hex']}  php {$expected}  <-- FAILED");
if ($expected !== $m['data_hex']) { $fail++; }

// The account list is the library's to define; this records it so a PHP port
// has something to build against rather than reverse-engineering from a trace.
printf("%-10s %d accounts, order/flags recorded in the vector file\n", 'ix accts', count($m['accounts']));

exit($fail === 0 ? 0 : 1);
